### ISSUE TITLE
Export to Garmin, heartrate missing

### ISSUE THREAD

**Issue by screamer333** [rolandsz/Mi-Fit-and-Zepp-workout-exporter#17]
if you would like to import exported GPX to Garmin Connect (GC), you will notice HR is missing.
this is due to the fact GC accepts HR only as INT, not with values these are exported by default with decimals, like 100.00.

to fix this, just update the line:
f"<gpxtpx:hr>{int(point.heart_rate)}</gpxtpx:hr>"

Also I have indentified few more "Workout types":
    if summary.type == 1:
        return "running"
    elif summary.type == 6:
        return "walking"
    elif summary.type == 9:
        return "cycling"
    elif summary.type == 10:
        return "indoor_cycling"
    elif summary.type == 16:
        return "other"
    elif summary.type == 23:
        return "indoor_rowing"
    elif summary.type == 92:
        return "badminton"
    elif summary.type == 8:
        return "treadmill_running"

**Comment by rolandsz** [comment]
Thanks! I added these changes in https://github.com/rolandsz/Mi-Fit-and-Zepp-workout-exporter/commit/daab25d5a776cec25d08f812c01abd81bac1c53c and https://github.com/rolandsz/Mi-Fit-and-Zepp-workout-exporter/commit/471daa1b4d0296b57b8c0f1896cef75c9cd74375.
