### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by ajsteele** [rolandsz/Mi-Fit-and-Zepp-workout-exporter#6]
When running the script, I get the output

```
Traceback (most recent call last):
  File "XXX\main.py", line 26, in <module>
    scraper.run()
  File "XXX\core\scraper.py", line 27, in run
    history = self.api.get_history()
  File "XXX\core\api.py", line 15, in get_history
    r.raise_for_status()
  File "C:\tools\miniconda3\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api-mifit-de2.huami.com/v1/sport/run/history.json?source=run.mifit.huami.com
```

With another value for the API key, I get a 401 error so I assume this is the right key. Might the API have changed since this was written? Any idea how to fix this?

Thanks!

**Comment by rolandsz** [comment]
Hi Andrew,

Could you please check if your application is using the endpoint `https://api-mifit-de2.huami.com` by analyzing the network requests?

**Comment by ajsteele** [comment]
Thanks for the prompt reply!

I’m just running `main.py` from your repo so it’s not my application as such! But I just did a confirmatory check of the network requests and it’s definitely pinging `https://api-mifit-de2.huami.com/v1/sport/run/history.json?source=run.mifit.huami.com`. Thanks in advance for any insights…

**Comment by rolandsz** [comment]
Thanks for checking the network requests! I suspected that the error might be related to the region choice upon signing up, but it looks like UK accounts are also using the `api-mifit-de2.huami.com` endpoint.

Could you please check which sign-in method you are using in Zepp / Mi Fit? The information should be available on the settings page.

There are multiple options:
- Email
- Mi
- WeChat
- Facebook
- Google
- LINE

I quickly tested it with Email and Mi Account, and the script seemed to be working.

**Comment by ajsteele** [comment]
I agree, I think the UK does use the `de2` endpoint, that’s where the requests from my phone are pointed when I tried sniffing them with Fiddler!

I originally logged in with just email and then added a Mi account while testing.

The only thing that could be an issue is that I didn’t root my phone to get access to either HTTPS intercepts on Fiddler or the Zepp data folder, so I ended up finding my API token via [https://user.huami.com/privacy2/index.html?loginPlatform=web&platform_app=com.xiaomi.hm.health&v=4.0.17#/](https://user.huami.com/privacy2/index.html?loginPlatform=web&platform_app=com.xiaomi.hm.health&v=4.0.17#/). There’s a cookie set which appears to contain the token, `apptoken=DQ…h; userid=7…8`, which may not be correct—but, as I mentioned in the original comment, changing the token to something else returns a 401 rather than 500 error. Can you see your access token in the cookies to that web access point?

Thanks so much for your help!

**Comment by rolandsz** [comment]
Thanks for suggesting the browser-based approach, I was not aware of it! It's a lot more convenient to use than the other methods.

I tried to log in with the token obtained from the cookies, and I received the 500 error as well. It turned out that the `appname` and `appPlatform` headers were missing, and those headers were expected by the server. I also realized that the endpoint is not necessarily regional, one can use `api-mifit.huami.com` and it works well for both web-based and application-based tokens. I pushed a fix in 23a675925d4663214a799caf2a23184e239b92df, please pull the latest changes and retry the export.

**Comment by ajsteele** [comment]
It works! Thank you!

And glad I managed to stumble across the key hidden in the browser!

**Comment by rolandsz** [comment]
Amazing! I'm happy to hear that it works for you.
